### ISSUE TITLE
MaxRecursion depth exceeded while parsing filename

### ISSUE THREAD

**Issue by ldotlopez** [wackou/guessit#209] opened 2015-07-03 17:22 UTC
The following filename causes guessit (using command line tool and actual python code) to crash:

<pre>
$ guessit '36 Vayadhinile (2015) [HD Rip. 500MB. x264. AAC. ESubs][SR Puli][Team SR].mkv'
…
  File "/home/luis/src/arroyo/env/src/guessit/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/home/luis/src/arroyo/env/src/guessit/guessit/matcher.py", line 276, in process_node
    tmp_node = MatchTree(value, span=partition_span, parent=node)
  File "/home/luis/src/arroyo/env/src/guessit/guessit/matchtree.py", line 83, in __init__
    self.guess = Guess()
  File "/home/luis/src/arroyo/env/src/guessit/guessit/guess.py", line 148, in __init__
    metadata_kwargs, kwargs = _split_kwargs(**kwargs)
  File "/home/luis/src/arroyo/env/src/guessit/guessit/guess.py", line 132, in _split_kwargs
    for prop in dir(GuessMetadata):
RuntimeError: maximum recursion depth exceeded while calling a Python object
</pre>

Using different switches to help guessit I obtain different results:
* With "-t movie" guessit parses the filename with correct results 
* With "-t episode" it crashes in the same way. I know that file is actually a movie but I believe that guessit shouldn't crash in that way

**Comment by fernandog** [comment] 2015-07-17 19:43
@Toilal having this in SR too. same issue or another one?

**Comment by Toilal** [comment] 2015-07-17 20:13
Please give us the filename that fails too. It may be the same, but also
another one...

**Comment by wackou** [comment] 2015-07-27 15:09
Recursion issue is fixed (duplicate of https://github.com/wackou/guessit/issues/212). It still won't autodetect the file type correctly (it will think it is an episode), this is similar to https://github.com/wackou/guessit/issues/188

**Comment by didyouexpectthat** [comment] 2015-08-29 01:28
Hi @wackou, I am still seeing this in the latest versions of SickRage (both master and develop version).

**Comment by Toilal** [comment] 2015-08-29 05:27
What is the guessit version ? And for which file ?

**Comment by didyouexpectthat** [comment] 2015-08-29 17:09
According to guessit/__version__.py, version = 0.11.0.dev0.
The pull says that they updated guessit to  f25e1b30c60f334ad378d1146a900797e8f76240.
Let me track down the file name. By the time I notice it, my logs are so flooded and it only saves a few 1 meg copies of the logs.

**Comment by didyouexpectthat** [comment] 2015-09-01 15:08
Hi @Toilal 

```
sickrage.log.8:2015-09-01 02:13:42 DEBUG    FINDSUBTITLES :: Checking if /tv/Two and a Half Men/s06e10.nfo exists: True
sickrage.log.8:2015-09-01 02:13:42 DEBUG    FINDSUBTITLES :: Checking if /tv/Two and a Half Men/s06e10-thumb.jpg exists: True
sickrage.log.8:2015-09-01 02:13:42 DEBUG    FINDSUBTITLES :: 72227: Downloading subtitles for S06E10
sickrage.log.8:2015-09-01 02:13:45 INFO     FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/Two and a Half Men/s06e10.mkv
sickrage.log.8:2015-09-01 02:13:45 ERROR    FINDSUBTITLES :: Traceback (most recent call last):
```

```
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 269, in process_node
    self.process_node(node, partial_span=relative_span)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 236, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_language.py", line 46, in guess_language
    guess = search_language(string, allowed_languages)
  File "/usr/share/sickrage/lib/guessit/language.py", line 277, in search_language
    for prop, language, lang, word in find_possible_languages(string, allowed_languages):
  File "/usr/share/sickrage/lib/guessit/language.py", line 251, in find_possible_languages
    elif lang == 'mul' or hasattr(lang, 'alpha2'):
  File "/usr/share/sickrage/lib/babelfish/language.py", line 159, in __eq__
    return str(self) == other
  File "/usr/share/sickrage/lib/babelfish/language.py", line 178, in __str__
    s = self.alpha2
  File "/usr/share/sickrage/lib/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/usr/share/sickrage/lib/babelfish/converters/__init__.py", line 236, in __getitem__
    if name in self.converters:
RuntimeError: maximum recursion depth exceeded
```

**Comment by Toilal** [comment] 2015-09-01 19:18
Could you make a dirty change in sources to display `self.movie_release_name` content in this stack element ?

```
  File "/usr/share/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
```

It doesn't seems to be `/tv/Two and a Half Men/s06e10.mkv` because it works like a charm from command line, with the guessit version from sickrage.

**Comment by Toilal** [comment] 2015-09-01 19:26
From reading source of subliminal, `self.movie_release_name` contains a response string from OpenSubtitles webservice. I really need to grab the exact value of this variable to fix the issue.

**Comment by didyouexpectthat** [comment] 2015-09-01 23:10
I just have another example here: https://doc.rotten.soy/dopiv.vhdl
I will make this change and then let you know any updates. Thanks.

**Comment by fernandog** [comment] 2015-09-01 23:24
@didyouexpectthat checkout develop branch and try to reproduce please

**Comment by didyouexpectthat** [comment] 2015-09-01 23:31
Hi Fernandog,
I was already on develop so I pulled the latest.
```root@sickrage:/usr/share/sickrage/lib/subliminal/providers# git pull
Updating 3570d67..daec87a
Fast-forward
 lib/subliminal/providers/opensubtitles.py | 1 +
 1 file changed, 1 insertion(+)
```

I will start SickRage back up and continue to monitor. Thanks.

**Comment by didyouexpectthat** [comment] 2015-09-02 00:42
Based on my previous doc.rotten.soy link, I noticed it occured with file /tv/The Walking Dead/s01e02.mkv so I went into SickRage and forced a subtitle search for that file.
https://doc.rotten.soy/ixipo.vhdl

Also, did a search from the commit https://github.com/SiCKRAGETV/SickRage/commit/daec87a4898fbb24ad3934cbbf2c397eb17398ae and I am not finding the actual output.

https://doc.rotten.soy/edihi.vhdl

**Comment by fernandog** [comment] 2015-09-02 00:44
@miigotu any idea?

**Comment by miigotu** [comment] 2015-09-02 01:09
@didyouexpectthat first, you need to git pull from `/usr/share/sickrage` not in a subdir.

**Comment by didyouexpectthat** [comment] 2015-09-02 01:29
It is not necessary to navigate to the root of the git to pull updates. 

```
root@sickrage:/usr/share/sickrage# git pull
Already up-to-date.
root@sickrage:/usr/share/sickrage# cat ./lib/subliminal/providers/opensubtitles.py | grep relese
        logger.info('Trying to guess movie relese name: %r ', self.movie_release_name)
root@sickrage:/usr/share/sickrage# git show
commit daec87a4898fbb24ad3934cbbf2c397eb17398ae
Author: Fernando <fernandog@users.noreply.github.com>
Date:   Tue Sep 1 20:24:06 2015 -0300

    Add log line requested by upstream dev

    https://github.com/wackou/guessit/issues/209#issuecomment-136832364

    @miigotu what if the file is avi or mp4? We fixed the mkv in line 61 and 69

diff --git a/lib/subliminal/providers/opensubtitles.py b/lib/subliminal/providers/opensubtitles.py
index 795799d..f763837 100644
--- a/lib/subliminal/providers/opensubtitles.py
+++ b/lib/subliminal/providers/opensubtitles.py
@@ -58,6 +58,7 @@ class OpenSubtitlesSubtitle(Subtitle):
             if video.episode and self.series_episode == video.episode:
                 matches.add('episode')
             # guess
+            logger.info('Trying to guess movie relese name: %r ', self.movie_release_name)
             matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
         # movie
         elif isinstance(video, Movie) and self.movie_kind == 'movie':

```

**Comment by miigotu** [comment] 2015-09-02 02:23
@didyouexpectthat problem is that we don't have subliminal logging set up and enabled in SR, so that logger.info will show nothing.

**Comment by miigotu** [comment] 2015-09-02 02:26
@fernandog did you change line 61 and 69 in the lib? that is done incorrectly, and we also do not patch libs in SR, we submit patches upstream.

**Comment by miigotu** [comment] 2015-09-02 02:52
@didyouexpectthat you can change this:
`logger.info('Trying to guess movie relese name: %r ', self.movie_release_name)`
to:
`print '### Release Name ### %s' % self.movie_release_name`

and then start it from terminal, and search for subtitles manually for that episode. The print will output into the terminal, not into your log.

**Comment by didyouexpectthat** [comment] 2015-09-02 04:18
Appears like maybe one of the search results returns a [cyrillic X](http://www.fileformat.info/info/unicode/char/0445/index.htm) and then it can't parse ascii. 

https://doc.rotten.soy/atudo.vhdl

**Comment by miigotu** [comment] 2015-09-02 04:34
Negative, SR is still using a (terrible) hack that makes the default encoding utf-8.

**Comment by Toilal** [comment] 2015-09-02 04:56
@didyouexpectthat The print instruction must use unicode, like this : 

print `u'### Release Name ### %s' % self.movie_release_name`

**Comment by didyouexpectthat** [comment] 2015-09-02 05:07
I did try that as well.  Same result.

```
21:34:03 INFO::Thread-15 :: Error occurred when downloading subtitles for: /tv/The Walking Dead/s01e02.mkv
21:34:03 ERROR::Thread-15 :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/share/sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/share/sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/share/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    print u'## Release Name ### %s' % self.movie_release_name
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/share/sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/share/sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/share/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    print u'## Release Name ### %s' % self.movie_release_name
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 23: ordinal not in range(128)
```

**Comment by Toilal** [comment] 2015-09-02 05:14
Which python version are you running ? on mine, no problem with this X character ...

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u0445'
х
>>> print u'%s' % (u'\u0445',)
х
>>> print '%s' % (u'\u0445',)
х
>>> 
```

But there's a `from __future__ import unicode_literals` import in subliminal file that can cause the issue ...

**Comment by didyouexpectthat** [comment] 2015-09-02 05:20
```
root@sickrage:/usr/share/sickrage# python -V
Python 2.7.9
root@sickrage:/usr/share/sickrage# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u0445'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 0: ordinal not in range(128)
```

So, I tried another host I have that runs 2.7.3, and it seems fine on that OS.
```
root@goliath:~# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> unicode(raw_input(), 'utf-8')
х
u'\u0445'
```

**Comment by didyouexpectthat** [comment] 2015-09-02 05:23
``
root@goliath:~# locale -a
C
C.UTF-8
en_US.utf8
POSIX
```

```
root@sickrage:/# locale -a
C
C.UTF-8
POSIX
``

Probably missing en_US.utf8 from the host on this one. Let me add it and try again.

**Comment by Toilal** [comment] 2015-09-02 05:24
It's probably that, because it works on my computer with a pyenv installed 2.7.9 version.

**Comment by didyouexpectthat** [comment] 2015-09-02 05:44
Ran `dpkg-reconfigure locales` and enabled en_US.UTF-8 there. Restarted. Shows up in locales -a now, but still refuses to print the character. 

```
root@sickrage:/# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u0445'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 0: ordinal not in range(128)
>>> quit()
root@sickrage:/# locale -a
C
C.UTF-8
POSIX
en_US.utf8
root@sickrage:/# locale-gen
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
root@sickrage:/# locale -a
C
C.UTF-8
POSIX
en_US.utf8
root@sickrage:/# locale-gen
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
root@sickrage:/# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u0445'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0445' in position 0: ordinal not in range(128)
```
Hmm.  Even after a reboot, I still can't seem to print unicode characters. 
The difference between those two hosts was Debian 7 and Debian 8.

**Comment by Toilal** [comment] 2015-09-02 05:52
I think you have to define this locale as default, but i'm not a linux guru don't know how to do that.

**Comment by Toilal** [comment] 2015-09-02 05:56
I think it can be done with `dpkg-reconfigure locales`

**Comment by Toilal** [comment] 2015-09-02 05:59
This answer may help : http://stackoverflow.com/questions/2596714/why-does-python-print-unicode-characters-when-the-default-encoding-is-ascii 

```
>>> import sys
>>> print sys.stdout.encoding
UTF-8
```

This should really give UTF-8.

**Comment by didyouexpectthat** [comment] 2015-09-02 06:04
I tried about a million things. `dpkg-reconfigure locales` just allowed me to run locale-gen (it removes a comment mark from /etc/locale.gen) and see it try to do stuff with UTF-8 but that was only part of the helpful getting it into locale.
The next problem I was having was just getting it to stay. On reboot, it was defaulting back to POSIX locale, for whatever reason.

```
root@sickrage:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
Though I have no idea where it is pulling the POSIX value from.
using `export LANG=en_US.UTF-8` worked only until restart, too.
I tried putting LANG=en_US.UTF-8 in /etc/locale.conf and restarting as well, but it would just not take. 
I ended up putting that export flag in `/root/.profile` Seems to have stayed this time.

```
root@sickrage:/#
root@sickrage:/# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@sickrage:/# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u0445'
х
```

Now this gives me
```
root@sickrage:/# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.stdout.encoding
UTF-8
```

Earlier, I ran that same command. The output was 
```
>>> import sys
>>> sys.stdout.encoding
'ANSI_X3.4-1968'
```

**Comment by Toilal** [comment] 2015-09-02 06:06
Seems to be good now, you are exactly in the case of the stackoverflow QA. Can you try to run sickrage now with this configuration ?

**Comment by Toilal** [comment] 2015-09-02 06:06
And give the content of the print (that really the only thing I need to start investigating :p)

**Comment by didyouexpectthat** [comment] 2015-09-02 06:11
https://gist.github.com/didyouexpectthat/b2372639a000799256c5

**Comment by Toilal** [comment] 2015-09-02 06:27
I can't reproduce with any of the displayed string :(

```
(2.7.9-sickrage)toilal@pc-ubuntu:~/IdeaProjects/SickRage/lib$ python -m guessit -t episode "The.Walking.Dead.S01.BDRip.XviD-SAiNTS (Whole).mkv" "The.Walking.Dead.S01E02.720p.BluRay.x264-SiNNERS.mkv" " The Walking Dead S1 E2.mkv" " The.Walking.Dead.S01E02.mkv" " The.Walking.Dead.S01E02.Guts.BDRip.XviD-SAiNTS.mkv" " the.walking.dead.s01e02.720p.hdtv.x264-ctu.mkv" " The.Walking.Dead.S01E02.RUS.BDRip.XviD.AC3.-HELLYWOOD.mkv" " The.Walking.Dead.s01e02.Guts.mkv" " 0102_-_So_Close,_Yet_So_Far_-__,__-_.mkv"
For: The.Walking.Dead.S01.BDRip.XviD-SAiNTS (Whole).mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "videoCodec": "XviD", 
    [1.00] "container": "mkv", 
    [0.60] "format": "BluRay", 
    [0.24] "series": "The Walking Dead", 
    [0.33] "releaseGroup": "SAiNTS(Whole)", 
    [0.36] "season": 1, 
    [1.00] "type": "episode"
}
For: The.Walking.Dead.S01E02.720p.BluRay.x264-SiNNERS.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [0.60] "videoCodec": "h264", 
    [1.00] "container": "mkv", 
    [0.60] "format": "BluRay", 
    [0.42] "series": "The Walking Dead", 
    [0.60] "releaseGroup": "SiNNERS", 
    [0.60] "screenSize": "720p", 
    [0.60] "season": 1, 
    [1.00] "type": "episode"
}
For:  The Walking Dead S1 E2.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [1.00] "container": "mkv", 
    [0.42] "series": "The Walking Dead", 
    [0.60] "season": 1, 
    [1.00] "type": "episode"
}
For:  The.Walking.Dead.S01E02.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [1.00] "container": "mkv", 
    [0.42] "series": "The Walking Dead", 
    [0.60] "season": 1, 
    [1.00] "type": "episode"
}
For:  The.Walking.Dead.S01E02.Guts.BDRip.XviD-SAiNTS.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [0.60] "videoCodec": "XviD", 
    [1.00] "container": "mkv", 
    [0.60] "format": "BluRay", 
    [0.42] "series": "The Walking Dead", 
    [0.30] "title": "Guts", 
    [0.60] "releaseGroup": "SAiNTS", 
    [0.60] "season": 1, 
    [1.00] "type": "episode"
}
For:  the.walking.dead.s01e02.720p.hdtv.x264-ctu.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [0.60] "videoCodec": "h264", 
    [1.00] "container": "mkv", 
    [0.60] "format": "HDTV", 
    [0.42] "series": "the walking dead", 
    [0.60] "releaseGroup": "ctu", 
    [0.60] "screenSize": "720p", 
    [0.60] "season": 1, 
    [1.00] "type": "episode"
}
For:  The.Walking.Dead.S01E02.RUS.BDRip.XviD.AC3.-HELLYWOOD.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [0.60] "videoCodec": "XviD", 
    [1.00] "container": "mkv", 
    [0.54] "language": [
        "ru"
    ], 
    [0.60] "format": "BluRay", 
    [0.42] "series": "The Walking Dead", 
    [0.42] "releaseGroup": "HELLYWOOD", 
    [0.60] "season": 1, 
    [1.00] "type": "episode", 
    [0.60] "audioCodec": "AC3"
}
For:  The.Walking.Dead.s01e02.Guts.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.60] "episodeNumber": 2, 
    [1.00] "container": "mkv", 
    [0.30] "title": "Guts", 
    [0.42] "series": "The Walking Dead", 
    [1.00] "type": "episode", 
    [0.60] "season": 1
}
For:  0102_-_So_Close,_Yet_So_Far_-__,__-_.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [0.36] "episodeNumber": 2, 
    [1.00] "container": "mkv", 
    [0.48] "language": [
        "so"
    ], 
    [0.24] "title": "Far", 
    [0.24] "series": "Close, Yet", 
    [0.36] "season": 1, 
    [1.00] "type": "episode"
}
```

**Comment by miigotu** [comment] 2015-09-02 07:07
I'll add a debug logger for subliminal and guessit in SR tomorrow and provide a patch, maybe we can find the true culprit then.

**Comment by Diaoul** [comment] 2015-09-02 09:03
Or you can run subliminal CLI on the file that causes the issue with the
--debug flag.

**Comment by Toilal** [comment] 2015-09-03 06:01
Thanks @Diaoul for the tip. I've managed to run subliminal CLI in my dev/debug environment and finally find the filename causing issue : ` Fear the Walking Dead - 01x02 - So Close, Yet So Far.REPACK-KILLERS.French.C.updated.Addic7ed.com.mkv` (Effectively makes guessit crash without so exclusion added by wackou yesterday 8ec4d7b642557fc4c0fee2f8ae9bdccc508d7850)

**Closed** 2015-09-03 20:33 UTC
Labels: Bug, Invalid Guess Result, P1 - Critical

**Comment by didyouexpectthat** [comment] 2015-09-04 04:54
Just as a comment, it was "The Walking Dead" s01e02 that I was having problems with. It looks like Toilal found another problem with "Fear the Walking Dead" s01e02 -- I will upgrade sickrage when I notice it is patched and see if I still run into the same issue.  The latest pull I did had some fixes for guessit, it looks like, so I will go over and investigate those. Thanks.

**Comment by Toilal** [comment] 2015-09-04 05:39
It will definitively fix your issue @didyouexpectthat, for sure.

In sickrage, you have "/tv/The Walking Dead/s01e02.mkv" as input, but this input get through subliminal to search for available subtitles for your langage. Inside subliminal, it make API requests to some subtitles services, like [opensubtitles](http://www.opensubtitles.org/) returning a list of possible release names from this search input.

**Each item** in this possible release names list is then **parsed with guessit**, to find out the best match for your subtitle search. In the list, there was `Fear the Walking Dead - 01x02 - So Close, Yet So Far.REPACK-KILLERS.French.C.updated.Addic7ed.com.mkv`, but those string list doesn't appear at all in your sickrage log ... 

This is this release name that caused the issue in guessit (Because of the So word appearing two times as a language code in the title ...).

**Comment by fernandog** [comment] 2015-09-04 21:56
another one. We must work together SR + subliminal + guessit to report this filenames
https://github.com/SiCKRAGETV/sickrage-issues/issues/2647
